/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dota.invoker;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author atifk
 */
public class SurvivalMode extends javax.swing.JFrame {
    
    private short counter;
    private short quasCounter;
    private short wexCounter;
    private short exortCounter;
    
    /**
     * Creates new form InvokerTrainerGUI
     */
    public SurvivalMode() {
        setFrameLocation();
        initComponents();
        displaySkill();
        setDefaultBorder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameModes = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        firstInvoke = new javax.swing.JLabel();
        secondInvoke = new javax.swing.JLabel();
        thirdInvoke = new javax.swing.JLabel();
        spell = new javax.swing.JLabel();
        spellNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Survival Mode");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(33, 33, 33));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Survival Mode");
        jLabel1.setToolTipText("Invoke the spell displayed within the time limit.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        jPanel2.setBackground(new java.awt.Color(33, 33, 33));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 353, 639, 90));

        jPanel3.setBackground(new java.awt.Color(66, 66, 66));

        firstInvoke.setForeground(new java.awt.Color(255, 0, 0));

        secondInvoke.setForeground(new java.awt.Color(255, 0, 0));

        thirdInvoke.setForeground(new java.awt.Color(255, 0, 0));

        spell.setBackground(new java.awt.Color(204, 204, 0));
        spell.setForeground(new java.awt.Color(255, 0, 0));
        spell.setBorder(new javax.swing.border.MatteBorder(null));

        spellNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        spellNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(spellNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(205, 205, 205)
                            .addComponent(firstInvoke, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(secondInvoke, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(thirdInvoke, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(spell, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(spell, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spellNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(secondInvoke, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(thirdInvoke, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(firstInvoke, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, 639, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        MainSpells spell = new MainSpells();
        String tempSpell = "";
        
        if (evt.getKeyCode() == KeyEvent.VK_Q) {
            tempSpell = spell.getSpell('Q');
            this.quasCounter++;
            setCounter();
            setPanelImage(tempSpell);
        }
        else if (evt.getKeyCode() == KeyEvent.VK_W) {
            tempSpell = spell.getSpell('W');
            this.wexCounter++;
            setCounter();
            setPanelImage(tempSpell);
        }
        else if (evt.getKeyCode() == KeyEvent.VK_E) {
            tempSpell = spell.getSpell('E');
            this.exortCounter++;
            setCounter();
            setPanelImage(tempSpell);
        }
        else if (evt.getKeyCode() == KeyEvent.VK_R) {
            AnswerCheck check = new AnswerCheck();
        }
    }//GEN-LAST:event_formKeyPressed
    
    private void setCounter() {
        if (this.counter < 3)
            this.counter++;
        else
            setDefaultBorder();
    }
    
    private void setPanelImage(String tempSpell) {
        String spellLocation;
        
        if (this.counter == 1) {
            spellLocation = "/com/dota/invoker/spell_icons/" 
                + tempSpell + ".png";
            firstInvoke.setIcon(new javax.swing.ImageIcon(getClass().getResource(spellLocation)));
        } else if (this.counter == 2) {
            spellLocation = "/com/dota/invoker/spell_icons/" 
                + tempSpell + ".png";
            secondInvoke.setIcon(new javax.swing.ImageIcon(getClass().getResource(spellLocation)));
        } else if (this.counter == 3) {
            spellLocation = "/com/dota/invoker/spell_icons/" 
                + tempSpell + ".png";
            thirdInvoke.setIcon(new javax.swing.ImageIcon(getClass().getResource(spellLocation)));
        }
    }
    
    private void setDefaultBorder() {
        this.counter = 0;
        quasCounter = 0;
        wexCounter = 0;
        exortCounter = 0;
        
        Border border = BorderFactory.createLineBorder(Color.BLACK);
        firstInvoke.setIcon(null);
        secondInvoke.setIcon(null);
        thirdInvoke.setIcon(null);
        
        firstInvoke.setBorder(border);
        secondInvoke.setBorder(border);
        thirdInvoke.setBorder(border);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SurvivalMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SurvivalMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SurvivalMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SurvivalMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SurvivalMode().setVisible(true);
            }
        });
    }
    
    private void setFrameLocation() {
        InvokerTrainerGUI it = new InvokerTrainerGUI();
        setLocation(it.getLocation());
    }
    
    private void displaySkill() {
        
        try {
            RandomSkill random = new RandomSkill();
            String temp = random.getRandomSkill(true);
            
            StringBuilder sb = new StringBuilder();
            
            for (int i = 0; i < temp.length(); i++) {
                if (temp.charAt(i) != '_')
                    sb.append(temp.charAt(i));
                else
                    sb.append(' ');
            }
            
            spellNameLabel.setText(sb.toString());
            
            String s = "/com/dota/invoker/spell_icons/" 
                    + temp + ".png";
            spell.setIcon(new javax.swing.ImageIcon(getClass().getResource(s)));
        }
        catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstInvoke;
    private javax.swing.ButtonGroup gameModes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel secondInvoke;
    private javax.swing.JLabel spell;
    private javax.swing.JLabel spellNameLabel;
    private javax.swing.JLabel thirdInvoke;
    // End of variables declaration//GEN-END:variables
}
